- include/abrt.h
- lib/abrt.c
> abrt: switch from 'analyzer' to 'type'

- lib/python_stacktrace.c
Signed-off-by: Martin Milata <mmilata@redhat.com>
> Fix memory leak in sr_python_stacktrace_free

- python/Makefile.am
> python3: fix CFLAGS on openSUSE

- lib/abrt.c
- lib/core_stacktrace.c
- lib/core_unwind.c
- lib/java_frame.c
- lib/koops_stacktrace.c
- lib/python_frame.c
- lib/rpm.c
- lib/utils.c
- python/py_gdb_stacktrace.c
- satyr.c
Signed-off-by: Martin Milata <mmilata@redhat.com>
> Fix defects found by coverity

- include/koops/stacktrace.h
- lib/koops_stacktrace.c
- tests/koops_stacktrace.at
> koops: Add new taint flags

- include/operating_system.h
- lib/operating_system.c
- tests/operating_system.at
VARIANT= and VARIANT_ID= fields are optional.
http://www.freedesktop.org/software/systemd/man/os-release.html
Related to abrt/abrt#995
> os: add support for OS Variant

- satyr.spec.in
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
> Build python3 only if supported

- lib/normalize.c
> normalization: actualize list of functions

- lib/python_stacktrace.c
> Check the return value of sr_parse_char_cspan

- RELEASE
> Update RELEASE notes

- lib/koops_frame.c
- tests/kerneloopses/arm-hung-task-oops
- tests/koops_frame.at
- tests/koops_stacktrace.at
Please see commit message, contains detailed description.
> Arm koops parse fix

- .gitignore
- Makefile.am
- apidoc/Doxyfile.in
- apidoc/Makefile.am
- apidoc/html/Makefile.am
- configure.ac
- include/abrt.h
- include/core/unwind.h
- include/frame.h
- include/js/platform.h
- include/js/stacktrace.h
- include/json.h
- include/operating_system.h
- include/report.h
- include/report_type.h
- include/ruby/stacktrace.h
- include/stacktrace.h
- include/thread.h
- satyr.spec.in
Related to #58
This PR arose as a result of review of PR #258 because of many mistakes in #258, which will be closed, it was simpler to open a new one.
> apidoc: generate html docs using doxygen

- satyr.spec.in
Taken from https://src.fedoraproject.org/rpms/satyr/pull-request/3#
Signed-off-by: Matej Marusak <mmarusak@redhat.com>
> spec: Update Python 2 dependency declarations

- lib/abrt.c
We've decided to attach python interpreter rpm information
to uReport as related package. Python developers need this
information in same cases.
Fixes abrt/abrt#1294
> Append Python interpreter as related package

- lib/json.c
> json: Fix crash when parsing invalid input

- Makefile.am
- satyr.spec.in
- Removes old provides for satyr-python3
- Replaces make commands with macros
> spec: Changes to spec file

- python/py_core_frame.h
- python/py_core_stacktrace.h
- python/py_core_thread.h
- python/py_gdb_frame.h
- python/py_gdb_stacktrace.h
- python/py_gdb_thread.h
- python/py_java_frame.h
- python/py_java_stacktrace.h
- python/py_java_thread.h
- python/py_js_frame.h
- python/py_js_stacktrace.h
- python/py_koops_frame.h
- python/py_koops_stacktrace.h
- python/py_operating_system.h
- python/py_python_frame.h
- python/py_python_stacktrace.h
- python/py_report.h
- python/py_rpm_package.h
- python/py_ruby_frame.h
- python/py_ruby_stacktrace.h
> Fix build failure with gcc -fno-common

- python/py_common.c
- python/py_common.h
- python/py_report.c
> Fix warnings when building with -Wdiscarded-qualifiers

- README.md
A minimal version of build instructions. Nothing interesting here, it's just that every project uses a slightly different method and I keep forgetting and digging around looking for a HOWTO.
> Add HACKING.md

- tests/dump_core.c
- tests/gdb_frame.c
- tests/js_frame.c
- tests/js_platform.c
- tests/js_stacktrace.c
- tests/normalize.c
- tests/report.c
- tests/utils.c
> Too many args to open

- satyr.spec.in
Related to https://github.com/abrt/abrt/issues/1519
> spec: Don't use GitHub-generated tarball as Source

- tests/metrics.c
The metrics test was relying on a peculiar behaviour of `va_list`:
A variadic function **A** would pass a `va_list` of args passed to it to
another function **B**. **B** would iterate over a part of the va_list, then
return. **A** would call **B** again, passing the same `va_list` and **B** would
continue iterating over the rest of it, picking up where it left off
after the last call. This seems to work fine on x86_64 but on some
architectures (e.g. ppc64le and i686), the second call to B restarts
the iteration from the beginning of the va_list, using the same data
twice.
(Tested with gcc 10.2.1 20201016 on both x86_64 and ppc64le.)
This commit replaces the passing of `va_list` as arg with string array,
removing the need of the callee to remember where to restart a previous
iteration. …
> tests: Don't pass va_list as function argument

- tests/metrics.c
> tests: Drop unused var

- satyr.spec.in
While we're at it ...
(https://github.com/abrt/abrt/commit/0debf3a94be7252ae59f7622e8612f6f)
> spec: Drop trailing comment

- README.md
> README: Document running testsuite in container

- satyr.spec.in
See [the wiki][1] for details.
[1]: https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
> Use SPDX format for license field
