abrt/satyr

lib/core_unwind.c
It looks like the fix (for rhbz#1129756, #163) in
2543c337e633fefe55c123b2f375a47fda8a884d was incomplete.
Fixes rhbz#1191586.
Signed-off-by: Martin Milata <mmilata@redhat.com>
=> unwind: fix unwinding of VDSO frames on i386 more

lib/core_unwind.c
Virtual DSOs do not have backing file on the filesystem. However
elfutils knows the name of the shared object (e.g. linux-gate.so.1) and
this is what we can use if the filename cannot be determined.
Fixes rhbz#1191586, related to #163.
Signed-off-by: Martin Milata <mmilata@redhat.com>
=> unwind: include filename for VDSOs

lib/koops_stacktrace.c, tests/kerneloopses/rhbz-1235021, tests/koops_stacktrace.at
https://bugzilla.redhat.com/show_bug.cgi?id=1235021
=> koops: fix parsing of modules if followed by "irq event stamp" line

lib/core_unwind.c
The documentation of dwfl_module_build_id() says:
This returns 0 when the module's main ELF file has not yet been loaded
and its build ID bits were not reported.  To ensure the ID is always
returned when determinable, call dwfl_module_getelf first.
/usr/include/elfutils/libdwfl.h
ABRT upstream commit 88c6b3683a129c0e369071204b29fbca94772d3b verifies
this patch.
Discovered by Richard Marko <rmarko@redhat.com>
Resolved by Mark Wielaard <mjw@redhat.com>
=> core_unwind: fix the missing frame build_id and file_name

include/core/frame.h, include/core/stacktrace.h, include/core/thread.h, include/gdb/frame.h, include/gdb/sharedlib.h, include/gdb/stacktrace.h, include/gdb/thread.h, include/java/frame.h, include/java/stacktrace.h, include/java/thread.h, include/koops/frame.h, include/koops/stacktrace.h, include/operating_system.h, include/python/frame.h, include/python/stacktrace.h, include/report.h, include/rpm.h, include/ruby/frame.h, include/ruby/stacktrace.h, include/strbuf.h, python/py_common.c, python/py_gdb_frame.c, python/py_gdb_frame.h, python/py_gdb_stacktrace.c, python/py_metrics.c, python/py_ruby_frame.c
include: function declaration isn’t a prototype
python: signed versus unsigned comparison
=> Fix compile warnings.

tests/core_stacktrace.at
gdb is no longer placed in /usr/bin but it's placed in /usr/libexec/gdb
=> testsuite: fix sr_core_stacktrace_from_gdb_limit test

include/abrt.h, include/core/unwind.h, lib/abrt.c, lib/core_unwind_elfutils.c
We need to divide the unwinding into too steps because we want to run
elfutils under unprivileged users in abrt-hook-ccpp.
This commit splits the unwinding into prepare and generate parts. The
prepare part includes attaching the process using PTRACE - this part
must be run under privileged users. The generate part includes unwinding.
With some modifications to elfutils, we might be able to run all
elfutils function under an unprivileged user.
Signed-off-by: Adam Sulc <xmineral@seznam.cz>
=> elfutils: run hook unwinding under unprivileged user

satyr.spec.in
Python [23] binary package was renamed to python[23]-satyr
See https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3
Signed-off-by: Martin Kutlak <mkutlak@redhat.com>
=> spec: rename Python binary packages

include/abrt.h, include/rpm.h, lib/abrt.c, lib/report.c, lib/rpm.c
We want to allow sending uReports for crashes from unpackaged
executables. To recognize such uReports we introduce 'unpackaged'
field.
We do this for customers who deploy own FAF server for binaries
which are not shiped within rpms.
=> Introduce 'unpackaged' field in uReport

tests/kerneloopses/arm-hung-task-oops-2, tests/koops_stacktrace.at
Processing of ARM kernel oopses was fixed few commits earlier
by commit: ca5c497bf70be9c61f1ed18676ef2bd8998c2c57, that time I was not
aware of existing bugzilla ticket rhbz#1353002.
This commit just adds testcase covering bugzilla #1353002 to prove it is
really fixed.
Closes #214.
=> add testcase for ARM kernel oops bz

lib/core_unwind.c
Commit f749d97f060e3c287eb700636790d61337b73eae added new functions
*_core_hook_prepare and *_core_hook_generate to replace a single
function *_core_hook. The *_core_hook was already stubbed out when
WITH_LIBDWFL or PTRACE_SEIZE was not defined, but the new commit did not
add matching stubs for the new functions that replaced it.
=> elfutils: Add missing stubs from earlier commit

Makefile.am, RELEASE
Adds make release-* commands to the Makefile.am (as abrt and libreport has) to ease and speedup
release process of satyr.
Update RELEASE notes, remove ChangeLog from it, since it is no more
present in the tree.
=> makefile: add make release-* subcommands

lib/elves.c, python/doc/satyr.py
some compilation warnings including red sea of python complains solved
2 still left in json.c, which I am not able to fix
try to build with and without this patch and you will see the difference
=> fix some compilation warnings

Makefile.am
make dist created a 'gz' tar archive but for satyr releasing 'xz' one is needed.
It was described in RELEASE guide commit fa7ae698b0ec19c07d6419d69c4b6e241ad45420
Signed-off-by: Martin Kutlak <mkutlak@redhat.com>
=> makefile: create .tar.xz with make release

include/utils.h, lib/java_frame.c, lib/js_frame.c, lib/normalize.c, lib/python_frame.c, lib/ruby_frame.c, lib/utils.c, tests/java_frame.at, tests/js_frame.at, tests/python/python.py, tests/python_stacktraces/python-01, tests/ruby_frame.at
In abrt/libreport#523 has been shown that ureports may leek sensitive data in ruby frames. This PR fixes that and also makes sure, that other frames do not leek that kind of data as well.
=> Anonymize filename

tests/core_stacktrace.at
The test failed on rawhide (gdb v8.1.50) with error message:
"A syntax error in expression, near `full'."
According to the GDB documentation the correct syntax for backtrace
command is `backtrace [full] n`.
- https://sourceware.org/gdb/onlinedocs/gdb/Backtrace.html
Signed-off-by: Martin Kutlak <mkutlak@redhat.com>
=> testsuite: Correct syntax for gdb backtrace command

lib/core_frame.c, lib/python_frame.c, tests/core_frame.at, tests/python/core.py, tests/python/python.py
Old core truncated backtrace format:
#1 crash in /usr/bin/will_segfault
#2 varargs in /usr/bin/will_segfault
#3 f in /usr/bin/will_segfault
#4 callback in /usr/bin/will_segfault
#5 call_me_back in /usr/lib64/libwillcrash.so.0.0.0
New core truncated backtrace format:
#1 [will_segfault] crash
#2 [will_segfault] varargs
#3 [will_segfault] f
#4 [will_segfault] callback
#5 [libwillcrash.so.0.0.0] call_me_back
Old python truncated backtrace format:
#1 crash in /home/mhabrnal/a.py:4
#2 a in /home/mhabrnal/a.py:7
#3 recursion in /home/mhabrnal/a.py:13
#4 recursion in /home/mhabrnal/a.py:11
#5 recursion in /home/mhabrnal/a.py:11
New python truncated backtrace format:
#1 [/home/mhabrnal/a.py:4] crash
#2 [/home/mhabrnal/a.py:7] a
#3 [/home/mhabrnal/a.py:13] recursion
#4 [/home/mhabrnal/a.py:11] …
=> Improve truncated backtrace format for python and core

lib/disasm.c
Fingerprinting support was dropped in
b50032ed5c115fe61f1b2e9809108ecf2abc3863, but the code was left in.
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> lib: disasm: Remove unused code

configure.ac, lib/Makefile.am, lib/elves.c, lib/internal_unwind.h
See commits, but mostly it’s cleaning up checks for obsolete libraries and minimizing auto-detection, which is morally and otherwise reprehensible and broken.
=> pkg-config-ify the build

lib/normalize.c
Should help with [1] not being associated with [2].
[1] https://retrace.fedoraproject.org/faf/reports/2581878/
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1133131
Signed-off-by: Martin Kutlak <mkutlak@redhat.com>
=> normalization: actualize list of functions

include/core/frame.h, lib/core_frame.c, lib/core_unwind.c, lib/distance.c, lib/elves.c, lib/gdb_frame.c, lib/gdb_sharedlib.c, lib/gdb_stacktrace.c, lib/json.c, lib/ruby_frame.c, lib/utils.c
* Use `*_MAX` constants instead of `-1` in unsigned comparisons.
* Use fitting types (`size_t`, `unsigned long`, etc.) where appropriate instead of the generic `int`.
* Correct parenthesization for bitfield tests.
* Document when a core stack frame's address may be unknown.
=> style: Various fixes suggested by Clang

include/json.h, lib/json.c, tests/Makefile.am, tests/json.at, tests/testsuite.at
This set of changes updates the JSON parser to the latest available version of [upstream](https://github.com/udp/json-parser/), dating to February 2018.
I migrated the upstream changes and interleaved them with modification done in satyr, paying special attention to code style and naming. I did not migrate support for parsing comments as it doesn't seem to be useful for satyr.
I also added a few unit tests for simple cases of valid and invalid inputs.
=> Update JSON parser to latest upstream version

.gitignore, configure.ac, lib/Makefile.am, lib/normalize.c, lib/normalize_hash.gperf, satyr.spec.in
Currently, we do tons of strcmp() calls when pruning traces. Not good
for performance, but we can instead hash things ahead of time to save
waste heat. gperf generates perfect hashes, so there will not be
collisions giving us trouble.
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> Use gperf during normalization

lib/koops_stacktrace.c, tests/kerneloopses/rhbz-1518943, tests/koops_stacktrace.at
As can be seen at [1], the kernel might also spill the value of CR2
*after* the list of modules. This commit adds a check for it to avoid
parsing a register as a module.
[1] - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/arch/x86/mm/fault.c?id=8e998fc24de47c55b47a887f6c95ab91acd4a720#n824
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1518943
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> lib: koops_stacktrace: Don’t parse register as module

lib/core_stacktrace.c
The executable string is never freed despite being duplicated from the
JSON object.
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> lib: core_stacktrace: Plug leak

Makefile.am, configure.ac, lib/Makefile.am, lib/distance.c, lib/sha1.c, lib/sha1.h, satyr.spec.in, tests/utils.at
Use an established crypto library in place of a bundled one. It is also about 50% faster according to quick microbenchmarks.
=> lib: Use Nettle for computing SHA-1 digests

tests/ruby_frame.at
ruby_frame.at:216:3: error: void function 'check' should not return a value [-Wreturn-type]
clang treates these as errors by default, so this was breaking the build with clang.
=> Fix -Wreturn-type warning

python/py_base_frame.c, python/py_base_stacktrace.c, python/py_base_thread.c, python/py_cluster.c, python/py_core_frame.c, python/py_core_stacktrace.c, python/py_core_thread.c, python/py_gdb_frame.c, python/py_gdb_sharedlib.c, python/py_gdb_stacktrace.c, python/py_gdb_thread.c, python/py_java_frame.c, python/py_java_stacktrace.c, python/py_java_thread.c, python/py_js_frame.c, python/py_js_stacktrace.c, python/py_koops_frame.c, python/py_koops_stacktrace.c, python/py_metrics.c, python/py_operating_system.c, python/py_python_frame.c, python/py_python_stacktrace.c, python/py_report.c, python/py_rpm_package.c, python/py_ruby_frame.c, python/py_ruby_stacktrace.c
The unused tp_print field in PyTypeObject has been replaced with
tp_vectorcall_offset and has a different type.
https://www.python.org/dev/peps/pep-0590/
=> python: Adapt to changes made in PEP 590

.github/workflows/check.yml, satyr.spec.in
This commit adds a GitHub Actions workflow to replace the Jenkins jobs
on the internal Red Hat instance. Though this does not use Mock, it
shouldn’t matter for our purposes.
=> Add GitHub Actions workflow for building PRs

Makefile.am, RELEASE, satyr.spec.in
Fallout from previous commit
However, `make rpm` still finishes with
"File not found: /home/mfabik/rpmbuild/BUILDROOT/satyr-0.31.15.gda1d87-1.fc32.x86_64/usr/share/doc/satyr/README.md"  
@msuchy, any ideas what can be causing this? I'm quite at a loss.
=> spec, RELEASE: README -> README.md

configure.ac, m4/ax_valgrind_check.m4, tests/Makefile.am, tests/local.at, tests/valgrind.supp
The first commit only applies to the tests that are still not dealt with in Ernestas's incomplete PR #298.  
The second commit adds the `check-valgrind` make target that applies to the changes in #298. Once #298 is finished, the changes in the first commit can be removed again.
=> make: add maintainer-check-valgrind make target

.git-commit-template, README.md
I like this feature and was missing it in Satyr. Also add instructions for contributing (and setting up the template) to `README`. All lifted almost verbatim from libreport.
=> Add commit message template

tests/utils.c
Using `%ld` with a var of type `size_t` causes a warning on platforms where
`size_t` isn't the same as `long int`.
=> tests: Use correct format specifier for size_t

satyr.spec.in
After the changes started in c465ace, spec-driven builds no longer
output the logs for failed tests as the logs are now stored in .log
files named after the corresponding test C source (and binary), rather
than in tests/testsuite.dir. This, however, doesn't apply to Python
bindings tests, which is why the `find` on tests/testsuite.dir is
retained.
=> spec: Output logs from failed tests

Makefile.am, satyr.spec.in
This way, when stuff is fixed in automake, the source tarball does not
need to be re-generated in upstream to use the fix.
Resolves rhbz#1898063
Patch contributed by Miro Hrončok <miro@hroncok.cz>
Lifted from e17dd1d8 in libreport
=> spec: Use autoreconf in %build

lib/cluster.c
Add an `assert()` to prevent calling `cluster_clean()` on a non-existent
struct. (And ISO C forbids zero-length arrays anyway.)
Also, initialize `clusters[0].objects` right after declaration.
GCC 11 complains about uninitialized variables when the initialization
happens in a lower scope (inside a loop in this case) than the call to
`free`, even when entering the lower scope is guaranteed.
=> sr_distances_cluster_objects: Check arg safety

configure.ac
Check for `elfutils/version.h` explicitly, as it's reportedly provided by the `elfutils` package on FreeBSD.
Resolves:
https://github.com/abrt/satyr/issues/326
=> configure: Add check for elfutils on FreeBSD

tests/python/core.py
The method `assertEquals()` has been deprecated since Python 3.2 and was removed in Python 3.11.
=> tests: Fix call to deprecated method

python/py_base_stacktrace.c
This file has references to g_free from glib-2.0 which needs this header
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> py_base_stacktrace.c: include glib.h

NEWS, gen-version, lib/Makefile.am, lib/normalize.c, python/py_gdb_stacktrace.c, satyr.spec.in
If we normalize the stacktrace, then we should also normalize
the crash frame.
Otherwise the normalized function name from the top thread frame
doesn't have to match with the same function name in the crash frame.
Example:
Normalized thread frame function name: __poll
Raw crash frame function name: __GI___poll
Resolves: rhbz#2168223
Signed-off-by: Michal Srb <michal@redhat.com>
=> Normalize both gdb stacktrace and the crash frame

NEWS, gen-version, lib/Makefile.am, lib/normalize.c, python/py_gdb_stacktrace.c, satyr.spec.in
When we normalize a stacktrace, we sometimes remove certain
frames. The problem is when crash frame is one of those
removed frames. In such cases, we simply cannot (reliably)
find the crash thread.
Therefore, before we normalize the stacktrace, we look
for the crash thread and remember its id. We can then
use that id later, if needed.
Related: rhbz#2168223
Fixes: #337
Signed-off-by: Michal Srb <michal@redhat.com>
=> Find crash thread before stacktrace is normalized

tests/dump_core.c
Use predefined macros`__clang__` to distinguish between clang and gcc to make sure the correct optimization attribute.
=> Fix test suit core_stacktrace fail using clang
